# Generated by Django 3.2.6 on 2022-09-16 21:13

from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=marketplace.models.marketplace_directory_path),
            preserve_default=False,
        ),
    ]
